# This file was generated by GoReleaser. DO NOT EDIT.
cask "mole" do
  name "mole"
  desc "A lightweight, pure Go implementation of an HTTP tunneling system"
  homepage "https://github.com/tsangpo/go-mole"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mole"

  on_macos do
    on_intel do
      url "https://github.com/tsangpo/go-mole/releases/download/v#{version}/go-mole_Darwin_x86_64.tar.gz"
      sha256 "c5e7b610b7a287cf422f53768f0565769003371a6fde0f50f53cfb0504a7ab3e"
    end
    on_arm do
      url "https://github.com/tsangpo/go-mole/releases/download/v#{version}/go-mole_Darwin_arm64.tar.gz"
      sha256 "fea0188faecf652bd1236fd7cbdf9360eb5fd88fd56a9a700dd45e3eb0a25601"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tsangpo/go-mole/releases/download/v#{version}/go-mole_Linux_x86_64.tar.gz"
      sha256 "78de95b681061709dcb34eabed197e6d8153ced933e501ea9730d6eedc6b86ab"
    end
    on_arm do
      url "https://github.com/tsangpo/go-mole/releases/download/v#{version}/go-mole_Linux_arm64.tar.gz"
      sha256 "20b6e50afda2fce9007ac515370cbc29c04434c6582bab9d3969d2392d365343"
    end
  end

  # No zap stanza required
end
