# This file was generated by GoReleaser. DO NOT EDIT.
cask "mole" do
  version "1.0.6"

  on_macos do
    on_arm do
      sha256 "6f074a1b412fbe3cb08ce7155aad1061b2fb28dadc28076cbe73c099ba601f22"
      url "https://github.com/tsangpo/homebrew-tap/releases/download/v#{version}/homebrew-tap_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "64d312095cb0d5944962553b1be1103797caedd823a450c28f8c7ebaa3dc049e"
      url "https://github.com/tsangpo/homebrew-tap/releases/download/v#{version}/homebrew-tap_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "958693aa40e7508e79213a9640c2da6df93cc1637c276c27148bfd0ad29d9097"
      url "https://github.com/tsangpo/homebrew-tap/releases/download/v#{version}/homebrew-tap_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c86dc38ffa136c0539202425cd6023c1ca65e53bae4237e47f172b39f5f11ede"
      url "https://github.com/tsangpo/homebrew-tap/releases/download/v#{version}/homebrew-tap_Linux_x86_64.tar.gz"
    end
  end

  name "mole"
  desc "A lightweight, pure Go implementation of an HTTP tunneling system"
  homepage "https://github.com/tsangpo/go-mole"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mole"

  # No zap stanza required
end
